name: Build and test

on:
  push:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
permissions: {}

jobs:
  build:
    name: Build and test
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v6.0.2
        with:
          persist-credentials: false
      - name: Set up XCode
        uses: maxim-lobanov/setup-xcode@ed7a3b1fda3918c0306d1b724322adc0b8cc0a90 # v1.7.0
        with:
          xcode-version: latest-stable

      - name: Test with strict concurrency
        run: |
          swift build -Xswiftc -strict-concurrency=complete
          swift test -Xswiftc -strict-concurrency=complete

      - name: List available simulator targets
        run: xcrun xctrace list devices

      - name: Test on iOS simulator
        run: xcodebuild test -scheme PowerSync-Package -destination "platform=iOS Simulator,name=iPhone 16"
      - name: Test on macOS simulator
        run: xcodebuild test -scheme PowerSync-Package -destination "platform=macOS,arch=arm64,name=My Mac"
      - name: Test on watchOS simulator
        run: xcodebuild test -scheme PowerSync-Package -destination "platform=watchOS Simulator,arch=arm64,name=Apple Watch Ultra 2 (49mm)"
      - name: Test on tvOS simulator
        run: xcodebuild test -scheme PowerSync-Package -destination "platform=tvOS Simulator,arch=arm64,name=Apple TV"
