name: Build and test

on:
  push:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
permissions: {}

jobs:
  zizmor:
    permissions:
      security-events: write # Needed to upload findings as code scanning results.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Run zizmor 🌈
        uses: zizmorcore/zizmor-action@b1d7e1fb5de872772f31590499237e7cce841e8e # v0.5.3
        with:
          persona: pedantic

  build:
    name: Build and test
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Set up XCode
        uses: maxim-lobanov/setup-xcode@ed7a3b1fda3918c0306d1b724322adc0b8cc0a90 # 1.7.0
        with:
          xcode-version: latest-stable

      - name: Test with strict concurrency
        run: |
          swift build -Xswiftc -strict-concurrency=complete
          swift test -Xswiftc -strict-concurrency=complete

      - name: List available simulator targets
        run: xcrun xctrace list devices

      - name: Test on iOS simulator
        run: xcodebuild test -scheme PowerSync-Package -destination "platform=iOS Simulator,name=iPhone 16"
      - name: Test on macOS simulator
        run: xcodebuild test -scheme PowerSync-Package -destination "platform=macOS,arch=arm64,name=My Mac"
      - name: Test on watchOS simulator
        run: xcodebuild test -scheme PowerSync-Package -destination "platform=watchOS Simulator,arch=arm64,name=Apple Watch Ultra 2 (49mm)"
      - name: Test on tvOS simulator
        run: xcodebuild test -scheme PowerSync-Package -destination "platform=tvOS Simulator,arch=arm64,name=Apple TV"
