name: Deploy Docs

on:
  push:

jobs:
  build:
    name: Build and test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docs
        run: |
          xcodebuild docbuild -scheme PowerSync -destination 'platform=macOS' -derivedDataPath ./DerivedData

      - name: Debug
        run: |
          ls -la ./DerivedData/Build/Products/Debug
          ls -la ./DerivedData/Build/Products/Debug/PowerSync.doccarchive

      - name: Process Docs
        run: |
          xcrun docc process-archive transform-for-static-hosting \                                           
          ./DerivedData/Build/Products/Debug/PowerSync.doccarchive \
          --output-path ./docs
